# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bullet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bullet
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'GeoFire', '>= 1.1'  

  target 'BulletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BulletUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
